---
generatorName: go

gitHost: github.com
gitUserId: bab3l
gitRepoId: go-netbox

packageName: netbox

globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: true
  modelTests: false

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: "false"
  generateInterfaces: "true"
  packageVersion: "4"
  enumClassPrefix: "true"
  useDefaultValuesForRequiredVars: "true"
